name: Docker Image from master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker images
      run: |
        docker login -u majst01 -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build -t metalstack/builder
        docker push metalstack/builder