name: Docker Image from master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the latest Docker image
      run: |
        docker build -t metalstack/builder .
    - name: Push the latest image
      run: |
        if [ "${{ secrets.DOCKER_HUB_TOKEN }}" != "undefined" -a "${{secrets.DOCKER_HUB_TOKEN }}" != "" ]; then
          docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push metalstack/builder
        fi