name: Docker Image from release tags

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push the released Docker images
      run: |
        if [ "${{ secrets.DOCKER_HUB_TOKEN }}" != "undefined" -a "${{secrets.DOCKER_HUB_TOKEN }}" != "" ]; then
          docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker build -t metalstack/builder:${GITHUB_HEAD_REF##*/} .
          docker push metalstack/builder:${GITHUB_HEAD_REF##*/}
        fi