name: Docker Image from release tags

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push the released Docker images
      run: |
        docker build -t metalstack/builder:${{ github.ref }} -t ghcr.io/metal-stack/builder:${{ github.ref }} .
        docker push metalstack/builder:${{ github.ref }}
        docker push ghcr.io/metal-stack/builder:${{ github.ref }}
