name: Docker Image from master

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker images
      run: |
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build -t metalstack/builder:${{ github.ref }} .
        docker push metalstack/builder:${{ github.ref }}